// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/nav/state/app_bootstrap_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i8;
import 'dart:ui' as _i6;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:two_eight_two/config/app_config.dart' as _i11;
import 'package:two_eight_two/enums/enums.dart' as _i9;
import 'package:two_eight_two/logging/logging.dart' as _i12;
import 'package:two_eight_two/models/models.dart' as _i2;
import 'package:two_eight_two/repos/repos.dart' as _i4;
import 'package:two_eight_two/screens/notifiers.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeError_0 extends _i1.SmartFake implements _i2.Error {
  _FakeError_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfig_1 extends _i1.SmartFake implements _i2.RemoteConfig {
  _FakeRemoteConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_2 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_3 extends _i1.SmartFake
    implements _i4.UserRepository {
  _FakeUserRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUserRepository_4 extends _i1.SmartFake
    implements _i4.BlockedUserRepository {
  _FakeBlockedUserRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRepository_5 extends _i1.SmartFake
    implements _i4.StorageRepository {
  _FakeStorageRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroRepository_6 extends _i1.SmartFake
    implements _i4.MunroRepository {
  _FakeMunroRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilterOptions_7 extends _i1.SmartFake implements _i2.FilterOptions {
  _FakeFilterOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroCompletionsRepository_8 extends _i1.SmartFake
    implements _i4.MunroCompletionsRepository {
  _FakeMunroCompletionsRepository_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_9 extends _i1.SmartFake implements _i3.UserState {
  _FakeUserState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteConfigState].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigState extends _i1.Mock implements _i3.RemoteConfigState {
  MockRemoteConfigState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RemoteConfigStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.RemoteConfigStatus.initial,
      ) as _i3.RemoteConfigStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  _i2.RemoteConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeRemoteConfig_1(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.RemoteConfig);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DeepLinkState].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkState extends _i1.Mock implements _i3.DeepLinkState {
  MockDeepLinkState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init({required bool? enableLogging}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#enableLogging: enableLogging},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsState extends _i1.Mock implements _i3.SettingsState {
  MockSettingsState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SettingsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.SettingsStatus.initial,
      ) as _i3.SettingsStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  bool get enablePushNotifications => (super.noSuchMethod(
        Invocation.getter(#enablePushNotifications),
        returnValue: false,
      ) as bool);

  @override
  bool get metricHeight => (super.noSuchMethod(
        Invocation.getter(#metricHeight),
        returnValue: false,
      ) as bool);

  @override
  bool get metricTemperature => (super.noSuchMethod(
        Invocation.getter(#metricTemperature),
        returnValue: false,
      ) as bool);

  @override
  String get defaultPostVisibility => (super.noSuchMethod(
        Invocation.getter(#defaultPostVisibility),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#defaultPostVisibility),
        ),
      ) as String);

  @override
  set setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i2.AppSettings? newAppSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [newAppSettings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setEnablePushNotifications(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setEnablePushNotifications,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMetricHeight(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMetricHeight,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMetricTemperature(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMetricTemperature,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setDefaultPostVisibility(String? v) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultPostVisibility,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthState extends _i1.Mock implements _i3.AuthState {
  MockAuthState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.AuthStatus.initial,
      ) as _i3.AuthStatus);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i3.AuthResult> registerWithEmail(
          {required _i2.RegistrationData? registrationData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [],
          {#registrationData: registrationData},
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #registerWithEmail,
            [],
            {#registrationData: registrationData},
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithApple,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> forgotPassword({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#email: email},
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> deleteUser(_i2.AppUser? appUser) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [appUser],
        ),
        returnValue: _i5.Future<_i3.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #deleteUser,
            [appUser],
          ),
        )),
      ) as _i5.Future<_i3.AuthResult>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserState extends _i1.Mock implements _i3.UserState {
  MockUserState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_3(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i4.UserRepository);

  @override
  _i4.BlockedUserRepository get blockedUserRepository => (super.noSuchMethod(
        Invocation.getter(#blockedUserRepository),
        returnValue: _FakeBlockedUserRepository_4(
          this,
          Invocation.getter(#blockedUserRepository),
        ),
      ) as _i4.BlockedUserRepository);

  @override
  _i4.StorageRepository get storageRepository => (super.noSuchMethod(
        Invocation.getter(#storageRepository),
        returnValue: _FakeStorageRepository_5(
          this,
          Invocation.getter(#storageRepository),
        ),
      ) as _i4.StorageRepository);

  @override
  _i3.UserStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.UserStatus.initial,
      ) as _i3.UserStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  List<String> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set setCurrentUser(_i2.AppUser? appUser) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentUser,
          appUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBlockedUsers(List<String>? blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #setBlockedUsers,
          blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> createUser({required _i2.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser({required _i2.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> readUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser({required _i2.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> blockUser({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfileVisibility(String? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [newValue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> updateProfile({
    required _i2.AppUser? appUser,
    _i8.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #appUser: appUser,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroState extends _i1.Mock implements _i3.MunroState {
  MockMunroState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MunroRepository get munroRepository => (super.noSuchMethod(
        Invocation.getter(#munroRepository),
        returnValue: _FakeMunroRepository_6(
          this,
          Invocation.getter(#munroRepository),
        ),
      ) as _i4.MunroRepository);

  @override
  _i3.MunroStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.MunroStatus.initial,
      ) as _i3.MunroStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  List<_i2.Munro> get munroList => (super.noSuchMethod(
        Invocation.getter(#munroList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  List<_i2.Munro> get filteredMunroList => (super.noSuchMethod(
        Invocation.getter(#filteredMunroList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  _i9.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i9.SortOrder.alphabetical,
      ) as _i9.SortOrder);

  @override
  _i2.FilterOptions get filterOptions => (super.noSuchMethod(
        Invocation.getter(#filterOptions),
        returnValue: _FakeFilterOptions_7(
          this,
          Invocation.getter(#filterOptions),
        ),
      ) as _i2.FilterOptions);

  @override
  bool get isFilterOptionsSet => (super.noSuchMethod(
        Invocation.getter(#isFilterOptionsSet),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.Munro> get createPostFilteredMunroList => (super.noSuchMethod(
        Invocation.getter(#createPostFilteredMunroList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  List<_i2.Munro> get bulkMunroUpdateList => (super.noSuchMethod(
        Invocation.getter(#bulkMunroUpdateList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  set setStatus(_i3.MunroStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setMunroList(List<_i2.Munro>? munroList) => super.noSuchMethod(
        Invocation.setter(
          #setMunroList,
          munroList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunro(_i2.Munro? selectedMunro) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunro,
          selectedMunro,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunroId(int? selectedMunroId) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunroId,
          selectedMunroId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setLatLngBounds(_i10.LatLngBounds? bounds) => super.noSuchMethod(
        Invocation.setter(
          #setLatLngBounds,
          bounds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSortOrder(_i9.SortOrder? sortOrder) => super.noSuchMethod(
        Invocation.setter(
          #setSortOrder,
          sortOrder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterOptions(_i2.FilterOptions? filterOptions) => super.noSuchMethod(
        Invocation.setter(
          #setFilterOptions,
          filterOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setGroupFilterMunroIds(List<int>? groupFilterMunroIds) =>
      super.noSuchMethod(
        Invocation.setter(
          #setGroupFilterMunroIds,
          groupFilterMunroIds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setCreatePostFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setCreatePostFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBulkMunroUpdateFilterString(String? filterString) =>
      super.noSuchMethod(
        Invocation.setter(
          #setBulkMunroUpdateFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadMunros() => (super.noSuchMethod(
        Invocation.method(
          #loadMunros,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void syncCompletedIds(Set<int>? ids) => super.noSuchMethod(
        Invocation.method(
          #syncCompletedIds,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilterAndSorting() => super.noSuchMethod(
        Invocation.method(
          #clearFilterAndSorting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroCompletionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroCompletionState extends _i1.Mock
    implements _i3.MunroCompletionState {
  MockMunroCompletionState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MunroCompletionsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMunroCompletionsRepository_8(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.MunroCompletionsRepository);

  @override
  _i3.UserState get userState => (super.noSuchMethod(
        Invocation.getter(#userState),
        returnValue: _FakeUserState_9(
          this,
          Invocation.getter(#userState),
        ),
      ) as _i3.UserState);

  @override
  _i3.MunroCompletionsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.MunroCompletionsStatus.initial,
      ) as _i3.MunroCompletionsStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  List<_i2.MunroCompletion> get munroCompletions => (super.noSuchMethod(
        Invocation.getter(#munroCompletions),
        returnValue: <_i2.MunroCompletion>[],
      ) as List<_i2.MunroCompletion>);

  @override
  Set<int> get completedMunroIds => (super.noSuchMethod(
        Invocation.getter(#completedMunroIds),
        returnValue: <int>{},
      ) as Set<int>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadUserMunroCompletions() => (super.noSuchMethod(
        Invocation.method(
          #loadUserMunroCompletions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addBulkCompletions(
          {required List<_i2.MunroCompletion>? munroCompletions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBulkCompletions,
          [],
          {#munroCompletions: munroCompletions},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markMunrosAsCompleted({
    required List<int>? munroIds,
    required DateTime? summitDateTime,
    String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMunrosAsCompleted,
          [],
          {
            #munroIds: munroIds,
            #summitDateTime: summitDateTime,
            #postId: postId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMunroCompletion(
          {required _i2.MunroCompletion? munroCompletion}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMunroCompletion,
          [],
          {#munroCompletion: munroCompletion},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCompletionsByMunroIdsAndPost({
    required List<int>? munroIds,
    required String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCompletionsByMunroIdsAndPost,
          [],
          {
            #munroIds: munroIds,
            #postId: postId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SavedListState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedListState extends _i1.Mock implements _i3.SavedListState {
  MockSavedListState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SavedListStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.SavedListStatus.initial,
      ) as _i3.SavedListStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  List<_i2.SavedList> get savedLists => (super.noSuchMethod(
        Invocation.getter(#savedLists),
        returnValue: <_i2.SavedList>[],
      ) as List<_i2.SavedList>);

  @override
  set setStatus(_i3.SavedListStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSavedLists(List<_i2.SavedList>? savedLists) => super.noSuchMethod(
        Invocation.setter(
          #setSavedLists,
          savedLists,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<dynamic> createSavedList({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSavedList,
          [],
          {#name: name},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> readUserSavedLists() => (super.noSuchMethod(
        Invocation.method(
          #readUserSavedLists,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> updateSavedListName(
          {required _i2.SavedList? savedList}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSavedListName,
          [],
          {#savedList: savedList},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> deleteSavedList({required _i2.SavedList? savedList}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSavedList,
          [],
          {#savedList: savedList},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> addMunroToSavedList({
    required _i2.SavedList? savedList,
    required int? munroId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMunroToSavedList,
          [],
          {
            #savedList: savedList,
            #munroId: munroId,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> removeMunroFromSavedList({
    required _i2.SavedList? savedList,
    required int? munroId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMunroFromSavedList,
          [],
          {
            #savedList: savedList,
            #munroId: munroId,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void removeSavedList(_i2.SavedList? savedList) => super.noSuchMethod(
        Invocation.method(
          #removeSavedList,
          [savedList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addSavedList(_i2.SavedList? savedList) => super.noSuchMethod(
        Invocation.method(
          #addSavedList,
          [savedList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSavedList(_i2.SavedList? savedList) => super.noSuchMethod(
        Invocation.method(
          #updateSavedList,
          [savedList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlavorState].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavorState extends _i1.Mock implements _i3.FlavorState {
  MockFlavorState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AppEnvironment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i11.AppEnvironment.dev,
      ) as _i11.AppEnvironment);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i12.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
