// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/nav/state/current_user_follower_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:two_eight_two/logging/logging.dart' as _i8;
import 'package:two_eight_two/models/models.dart' as _i3;
import 'package:two_eight_two/repos/repos.dart' as _i2;
import 'package:two_eight_two/screens/auth/state/user_state.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUserRepository_1 extends _i1.SmartFake
    implements _i2.BlockedUserRepository {
  _FakeBlockedUserRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRepository_2 extends _i1.SmartFake
    implements _i2.StorageRepository {
  _FakeStorageRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeError_3 extends _i1.SmartFake implements _i3.Error {
  _FakeError_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FollowersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowersRepository extends _i1.Mock
    implements _i2.FollowersRepository {
  MockFollowersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> relationshipExists({
    required String? sourceId,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #relationshipExists,
          [],
          {
            #sourceId: sourceId,
            #targetId: targetId,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<dynamic> create(
          {required _i3.FollowingRelationship? followingRelationship}) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#followingRelationship: followingRelationship},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> delete({
    required String? sourceId,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #sourceId: sourceId,
            #targetId: targetId,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<List<_i3.FollowingRelationship>> getFollowersFromUid({
    required String? targetId,
    required List<String>? excludedUserIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowersFromUid,
          [],
          {
            #targetId: targetId,
            #excludedUserIds: excludedUserIds,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i3.FollowingRelationship>>.value(
            <_i3.FollowingRelationship>[]),
      ) as _i4.Future<List<_i3.FollowingRelationship>>);

  @override
  _i4.Future<List<_i3.FollowingRelationship>> getFollowingFromUid({
    required String? sourceId,
    required List<String>? excludedUserIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowingFromUid,
          [],
          {
            #sourceId: sourceId,
            #excludedUserIds: excludedUserIds,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i3.FollowingRelationship>>.value(
            <_i3.FollowingRelationship>[]),
      ) as _i4.Future<List<_i3.FollowingRelationship>>);

  @override
  _i4.Future<List<_i3.FollowingRelationship>> getAllFollowingFromUid({
    required String? sourceId,
    required List<String>? excludedUserIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFollowingFromUid,
          [],
          {
            #sourceId: sourceId,
            #excludedUserIds: excludedUserIds,
          },
        ),
        returnValue: _i4.Future<List<_i3.FollowingRelationship>>.value(
            <_i3.FollowingRelationship>[]),
      ) as _i4.Future<List<_i3.FollowingRelationship>>);

  @override
  _i4.Future<List<_i3.FollowingRelationship>> searchFollowing({
    required String? sourceId,
    required String? searchTerm,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFollowing,
          [],
          {
            #sourceId: sourceId,
            #searchTerm: searchTerm,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i3.FollowingRelationship>>.value(
            <_i3.FollowingRelationship>[]),
      ) as _i4.Future<List<_i3.FollowingRelationship>>);
}

/// A class which mocks [UserState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserState extends _i1.Mock implements _i5.UserState {
  MockUserState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);

  @override
  _i2.BlockedUserRepository get blockedUserRepository => (super.noSuchMethod(
        Invocation.getter(#blockedUserRepository),
        returnValue: _FakeBlockedUserRepository_1(
          this,
          Invocation.getter(#blockedUserRepository),
        ),
      ) as _i2.BlockedUserRepository);

  @override
  _i2.StorageRepository get storageRepository => (super.noSuchMethod(
        Invocation.getter(#storageRepository),
        returnValue: _FakeStorageRepository_2(
          this,
          Invocation.getter(#storageRepository),
        ),
      ) as _i2.StorageRepository);

  @override
  _i5.UserStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.UserStatus.initial,
      ) as _i5.UserStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<String> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set setCurrentUser(_i3.AppUser? appUser) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentUser,
          appUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBlockedUsers(List<String>? blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #setBlockedUsers,
          blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> createUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> readUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfileVisibility(String? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [newValue],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> updateProfile({
    required _i3.AppUser? appUser,
    _i6.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #appUser: appUser,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i8.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
