// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/nav/state/deep_link_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:collection' as _i2;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:two_eight_two/logging/logging.dart' as _i8;
import 'package:two_eight_two/models/models.dart' as _i5;
import 'package:two_eight_two/repos/deep_link_repository.dart' as _i3;
import 'package:two_eight_two/screens/nav/state/app_intent_state.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUnmodifiableListView_0<E> extends _i1.SmartFake
    implements _i2.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeepLinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkRepository extends _i1.Mock
    implements _i3.DeepLinkRepository {
  MockDeepLinkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AppIntent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i4.Stream<_i5.AppIntent>.empty(),
      ) as _i4.Stream<_i5.AppIntent>);

  @override
  _i4.Future<void> init({required bool? enableLogging}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#enableLogging: enableLogging},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AppIntentState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppIntentState extends _i1.Mock implements _i6.AppIntentState {
  MockAppIntentState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UnmodifiableListView<_i5.AppIntent> get pending => (super.noSuchMethod(
        Invocation.getter(#pending),
        returnValue: _FakeUnmodifiableListView_0<_i5.AppIntent>(
          this,
          Invocation.getter(#pending),
        ),
      ) as _i2.UnmodifiableListView<_i5.AppIntent>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void enqueue(_i5.AppIntent? intent) => super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [intent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i8.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
