// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/nav/state/startup_overlay_policies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:collection' as _i3;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:two_eight_two/models/models.dart' as _i2;
import 'package:two_eight_two/repos/repos.dart' as _i8;
import 'package:two_eight_two/screens/nav/state/overlay_intent_state.dart'
    as _i7;
import 'package:two_eight_two/screens/nav/state/remote_config_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeError_0 extends _i1.SmartFake implements _i2.Error {
  _FakeError_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfig_1 extends _i1.SmartFake implements _i2.RemoteConfig {
  _FakeRemoteConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableListView_2<E> extends _i1.SmartFake
    implements _i3.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteConfigState].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigState extends _i1.Mock implements _i4.RemoteConfigState {
  MockRemoteConfigState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RemoteConfigStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.RemoteConfigStatus.initial,
      ) as _i4.RemoteConfigStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  _i2.RemoteConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeRemoteConfig_1(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.RemoteConfig);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OverlayIntentState].
///
/// See the documentation for Mockito's code generation for more information.
class MockOverlayIntentState extends _i1.Mock
    implements _i7.OverlayIntentState {
  MockOverlayIntentState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UnmodifiableListView<_i2.OverlayIntent> get pending =>
      (super.noSuchMethod(
        Invocation.getter(#pending),
        returnValue: _FakeUnmodifiableListView_2<_i2.OverlayIntent>(
          this,
          Invocation.getter(#pending),
        ),
      ) as _i3.UnmodifiableListView<_i2.OverlayIntent>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void enqueue(_i2.OverlayIntent? intent) => super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [intent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppFlagsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFlagsRepository extends _i1.Mock
    implements _i8.AppFlagsRepository {
  MockAppFlagsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mapTerrain => (super.noSuchMethod(
        Invocation.getter(#mapTerrain),
        returnValue: false,
      ) as bool);

  @override
  bool get showBulkMunroDialog => (super.noSuchMethod(
        Invocation.getter(#showBulkMunroDialog),
        returnValue: false,
      ) as bool);

  @override
  int get lastFeedbackSurveyNumber => (super.noSuchMethod(
        Invocation.getter(#lastFeedbackSurveyNumber),
        returnValue: 0,
      ) as int);

  @override
  String get lastAppUpdateDialogDate => (super.noSuchMethod(
        Invocation.getter(#lastAppUpdateDialogDate),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#lastAppUpdateDialogDate),
        ),
      ) as String);

  @override
  int get openCount => (super.noSuchMethod(
        Invocation.getter(#openCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> setMapTerrain(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMapTerrain,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setShowBulkMunroDialog(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setShowBulkMunroDialog,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLastFeedbackSurveyNumber(int? v) => (super.noSuchMethod(
        Invocation.method(
          #setLastFeedbackSurveyNumber,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLastAppUpdateDialogDate(String? isoDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastAppUpdateDialogDate,
          [isoDate],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool showWhatsNewDialog(String? version) => (super.noSuchMethod(
        Invocation.method(
          #showWhatsNewDialog,
          [version],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setShownWhatsNewDialog(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShownWhatsNewDialog,
          [version],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFirstAppVersion(String? v) => (super.noSuchMethod(
        Invocation.method(
          #setFirstAppVersion,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool showInAppOnboarding(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #showInAppOnboarding,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setShowInAppOnboarding(
    String? userId,
    bool? v,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowInAppOnboarding,
          [
            userId,
            v,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setOpenCount(int? v) => (super.noSuchMethod(
        Invocation.method(
          #setOpenCount,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementOpenCount() => (super.noSuchMethod(
        Invocation.method(
          #incrementOpenCount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AppInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppInfoRepository extends _i1.Mock implements _i8.AppInfoRepository {
  MockAppInfoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  int get buildNumber => (super.noSuchMethod(
        Invocation.getter(#buildNumber),
        returnValue: 0,
      ) as int);
}
