// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/settings/state/settings_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:two_eight_two/logging/logger.dart' as _i5;
import 'package:two_eight_two/models/models.dart' as _i2;
import 'package:two_eight_two/repos/settings_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _FakeAppSettings_0(
          this,
          Invocation.method(
            #load,
            [],
          ),
        ),
      ) as _i2.AppSettings);

  @override
  _i4.Future<void> save(_i2.AppSettings? s) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [s],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i5.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );
}
