// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/in_app_onboarding/state/in_app_onboarding_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:two_eight_two/analytics/analytics.dart' as _i12;
import 'package:two_eight_two/enums/enums.dart' as _i8;
import 'package:two_eight_two/logging/logging.dart' as _i13;
import 'package:two_eight_two/models/models.dart' as _i3;
import 'package:two_eight_two/push/push_notifications_state.dart' as _i11;
import 'package:two_eight_two/repos/repos.dart' as _i2;
import 'package:two_eight_two/screens/notifiers.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUserRepository_1 extends _i1.SmartFake
    implements _i2.BlockedUserRepository {
  _FakeBlockedUserRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRepository_2 extends _i1.SmartFake
    implements _i2.StorageRepository {
  _FakeStorageRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeError_3 extends _i1.SmartFake implements _i3.Error {
  _FakeError_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroCompletionsRepository_4 extends _i1.SmartFake
    implements _i2.MunroCompletionsRepository {
  _FakeMunroCompletionsRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_5 extends _i1.SmartFake implements _i4.UserState {
  _FakeUserState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroRepository_6 extends _i1.SmartFake
    implements _i2.MunroRepository {
  _FakeMunroRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilterOptions_7 extends _i1.SmartFake implements _i3.FilterOptions {
  _FakeFilterOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserState extends _i1.Mock implements _i4.UserState {
  MockUserState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);

  @override
  _i2.BlockedUserRepository get blockedUserRepository => (super.noSuchMethod(
        Invocation.getter(#blockedUserRepository),
        returnValue: _FakeBlockedUserRepository_1(
          this,
          Invocation.getter(#blockedUserRepository),
        ),
      ) as _i2.BlockedUserRepository);

  @override
  _i2.StorageRepository get storageRepository => (super.noSuchMethod(
        Invocation.getter(#storageRepository),
        returnValue: _FakeStorageRepository_2(
          this,
          Invocation.getter(#storageRepository),
        ),
      ) as _i2.StorageRepository);

  @override
  _i4.UserStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.UserStatus.initial,
      ) as _i4.UserStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<String> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set setCurrentUser(_i3.AppUser? appUser) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentUser,
          appUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBlockedUsers(List<String>? blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #setBlockedUsers,
          blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> createUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> readUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> blockUser({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfileVisibility(String? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [newValue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> updateProfile({
    required _i3.AppUser? appUser,
    _i6.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #appUser: appUser,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroCompletionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroCompletionState extends _i1.Mock
    implements _i4.MunroCompletionState {
  MockMunroCompletionState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MunroCompletionsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMunroCompletionsRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MunroCompletionsRepository);

  @override
  _i4.UserState get userState => (super.noSuchMethod(
        Invocation.getter(#userState),
        returnValue: _FakeUserState_5(
          this,
          Invocation.getter(#userState),
        ),
      ) as _i4.UserState);

  @override
  _i4.MunroCompletionsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.MunroCompletionsStatus.initial,
      ) as _i4.MunroCompletionsStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<_i3.MunroCompletion> get munroCompletions => (super.noSuchMethod(
        Invocation.getter(#munroCompletions),
        returnValue: <_i3.MunroCompletion>[],
      ) as List<_i3.MunroCompletion>);

  @override
  Set<int> get completedMunroIds => (super.noSuchMethod(
        Invocation.getter(#completedMunroIds),
        returnValue: <int>{},
      ) as Set<int>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadUserMunroCompletions() => (super.noSuchMethod(
        Invocation.method(
          #loadUserMunroCompletions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addBulkCompletions(
          {required List<_i3.MunroCompletion>? munroCompletions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBulkCompletions,
          [],
          {#munroCompletions: munroCompletions},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markMunrosAsCompleted({
    required List<int>? munroIds,
    required DateTime? summitDateTime,
    String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMunrosAsCompleted,
          [],
          {
            #munroIds: munroIds,
            #summitDateTime: summitDateTime,
            #postId: postId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMunroCompletion(
          {required _i3.MunroCompletion? munroCompletion}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMunroCompletion,
          [],
          {#munroCompletion: munroCompletion},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCompletionsByMunroIdsAndPost({
    required List<int>? munroIds,
    required String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCompletionsByMunroIdsAndPost,
          [],
          {
            #munroIds: munroIds,
            #postId: postId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BulkMunroUpdateState].
///
/// See the documentation for Mockito's code generation for more information.
class MockBulkMunroUpdateState extends _i1.Mock
    implements _i4.BulkMunroUpdateState {
  MockBulkMunroUpdateState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BulkMunroUpdateStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.BulkMunroUpdateStatus.initial,
      ) as _i4.BulkMunroUpdateStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<_i3.MunroCompletion> get startingBulkMunroUpdateList =>
      (super.noSuchMethod(
        Invocation.getter(#startingBulkMunroUpdateList),
        returnValue: <_i3.MunroCompletion>[],
      ) as List<_i3.MunroCompletion>);

  @override
  List<_i3.MunroCompletion> get bulkMunroUpdateList => (super.noSuchMethod(
        Invocation.getter(#bulkMunroUpdateList),
        returnValue: <_i3.MunroCompletion>[],
      ) as List<_i3.MunroCompletion>);

  @override
  List<_i3.MunroCompletion> get addedMunroCompletions => (super.noSuchMethod(
        Invocation.getter(#addedMunroCompletions),
        returnValue: <_i3.MunroCompletion>[],
      ) as List<_i3.MunroCompletion>);

  @override
  set setStatus(_i4.BulkMunroUpdateStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setStartingBulkMunroUpdateList(
          List<_i3.MunroCompletion>? bulkMunroUpdateList) =>
      super.noSuchMethod(
        Invocation.setter(
          #setStartingBulkMunroUpdateList,
          bulkMunroUpdateList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void addMunroCompleted(_i3.MunroCompletion? munroCompletion) =>
      super.noSuchMethod(
        Invocation.method(
          #addMunroCompleted,
          [munroCompletion],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateMunroCompleted(_i3.MunroCompletion? munroCompletion) =>
      super.noSuchMethod(
        Invocation.method(
          #updateMunroCompleted,
          [munroCompletion],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeMunroCompletion(int? id) => super.noSuchMethod(
        Invocation.method(
          #removeMunroCompletion,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AchievementsState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementsState extends _i1.Mock implements _i4.AchievementsState {
  MockAchievementsState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AchievementsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.AchievementsStatus.initial,
      ) as _i4.AchievementsStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<_i3.Achievement> get achievements => (super.noSuchMethod(
        Invocation.getter(#achievements),
        returnValue: <_i3.Achievement>[],
      ) as List<_i3.Achievement>);

  @override
  int get achievementFormCount => (super.noSuchMethod(
        Invocation.getter(#achievementFormCount),
        returnValue: 0,
      ) as int);

  @override
  set setStatus(_i4.AchievementsStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setAchievements(List<_i3.Achievement>? achievements) =>
      super.noSuchMethod(
        Invocation.setter(
          #setAchievements,
          achievements,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setCurrentAchievement(_i3.Achievement? achievement) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentAchievement,
          achievement,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setAchievementFormCount(int? achievementFormCount) => super.noSuchMethod(
        Invocation.setter(
          #setAchievementFormCount,
          achievementFormCount,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<dynamic> getUserAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getUserAchievements,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<void> acknowledgeAchievement(
          {required _i3.Achievement? achievement}) =>
      (super.noSuchMethod(
        Invocation.method(
          #acknowledgeAchievement,
          [],
          {#achievement: achievement},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unacknowledgeAchievement(
          {required _i3.Achievement? achievement}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unacknowledgeAchievement,
          [],
          {#achievement: achievement},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMunroChallenge() => (super.noSuchMethod(
        Invocation.method(
          #setMunroChallenge,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetAll() => super.noSuchMethod(
        Invocation.method(
          #resetAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserAchievementsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserAchievementsRepository extends _i1.Mock
    implements _i2.UserAchievementsRepository {
  MockUserAchievementsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Achievement>> getUserAchievements(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAchievements,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i5.Future<List<_i3.Achievement>>.value(<_i3.Achievement>[]),
      ) as _i5.Future<List<_i3.Achievement>>);

  @override
  _i5.Future<_i3.Achievement?> getLatestMunroChallengeAchievement(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestMunroChallengeAchievement,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<_i3.Achievement?>.value(),
      ) as _i5.Future<_i3.Achievement?>);

  @override
  _i5.Future<void> updateUserAchievement(
          {required _i3.Achievement? achievement}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserAchievement,
          [],
          {#achievement: achievement},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [MunroState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroState extends _i1.Mock implements _i4.MunroState {
  MockMunroState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MunroRepository get munroRepository => (super.noSuchMethod(
        Invocation.getter(#munroRepository),
        returnValue: _FakeMunroRepository_6(
          this,
          Invocation.getter(#munroRepository),
        ),
      ) as _i2.MunroRepository);

  @override
  _i4.MunroStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.MunroStatus.initial,
      ) as _i4.MunroStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<_i3.Munro> get munroList => (super.noSuchMethod(
        Invocation.getter(#munroList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  List<_i3.Munro> get filteredMunroList => (super.noSuchMethod(
        Invocation.getter(#filteredMunroList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  _i8.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i8.SortOrder.alphabetical,
      ) as _i8.SortOrder);

  @override
  _i3.FilterOptions get filterOptions => (super.noSuchMethod(
        Invocation.getter(#filterOptions),
        returnValue: _FakeFilterOptions_7(
          this,
          Invocation.getter(#filterOptions),
        ),
      ) as _i3.FilterOptions);

  @override
  bool get isFilterOptionsSet => (super.noSuchMethod(
        Invocation.getter(#isFilterOptionsSet),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.Munro> get createPostFilteredMunroList => (super.noSuchMethod(
        Invocation.getter(#createPostFilteredMunroList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  List<_i3.Munro> get bulkMunroUpdateList => (super.noSuchMethod(
        Invocation.getter(#bulkMunroUpdateList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  set setStatus(_i4.MunroStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setMunroList(List<_i3.Munro>? munroList) => super.noSuchMethod(
        Invocation.setter(
          #setMunroList,
          munroList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunro(_i3.Munro? selectedMunro) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunro,
          selectedMunro,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunroId(int? selectedMunroId) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunroId,
          selectedMunroId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setLatLngBounds(_i9.LatLngBounds? bounds) => super.noSuchMethod(
        Invocation.setter(
          #setLatLngBounds,
          bounds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSortOrder(_i8.SortOrder? sortOrder) => super.noSuchMethod(
        Invocation.setter(
          #setSortOrder,
          sortOrder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterOptions(_i3.FilterOptions? filterOptions) => super.noSuchMethod(
        Invocation.setter(
          #setFilterOptions,
          filterOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setGroupFilterMunroIds(List<int>? groupFilterMunroIds) =>
      super.noSuchMethod(
        Invocation.setter(
          #setGroupFilterMunroIds,
          groupFilterMunroIds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setCreatePostFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setCreatePostFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBulkMunroUpdateFilterString(String? filterString) =>
      super.noSuchMethod(
        Invocation.setter(
          #setBulkMunroUpdateFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadMunros() => (super.noSuchMethod(
        Invocation.method(
          #loadMunros,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void syncCompletedIds(Set<int>? ids) => super.noSuchMethod(
        Invocation.method(
          #syncCompletedIds,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilterAndSorting() => super.noSuchMethod(
        Invocation.method(
          #clearFilterAndSorting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppFlagsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFlagsRepository extends _i1.Mock
    implements _i2.AppFlagsRepository {
  MockAppFlagsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mapTerrain => (super.noSuchMethod(
        Invocation.getter(#mapTerrain),
        returnValue: false,
      ) as bool);

  @override
  bool get showBulkMunroDialog => (super.noSuchMethod(
        Invocation.getter(#showBulkMunroDialog),
        returnValue: false,
      ) as bool);

  @override
  int get lastFeedbackSurveyNumber => (super.noSuchMethod(
        Invocation.getter(#lastFeedbackSurveyNumber),
        returnValue: 0,
      ) as int);

  @override
  String get lastAppUpdateDialogDate => (super.noSuchMethod(
        Invocation.getter(#lastAppUpdateDialogDate),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#lastAppUpdateDialogDate),
        ),
      ) as String);

  @override
  int get openCount => (super.noSuchMethod(
        Invocation.getter(#openCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> setMapTerrain(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMapTerrain,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setShowBulkMunroDialog(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setShowBulkMunroDialog,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLastFeedbackSurveyNumber(int? v) => (super.noSuchMethod(
        Invocation.method(
          #setLastFeedbackSurveyNumber,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLastAppUpdateDialogDate(String? isoDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastAppUpdateDialogDate,
          [isoDate],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool showWhatsNewDialog(String? version) => (super.noSuchMethod(
        Invocation.method(
          #showWhatsNewDialog,
          [version],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setShownWhatsNewDialog(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShownWhatsNewDialog,
          [version],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFirstAppVersion(String? v) => (super.noSuchMethod(
        Invocation.method(
          #setFirstAppVersion,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool showInAppOnboarding(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #showInAppOnboarding,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setShowInAppOnboarding(
    String? userId,
    bool? v,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowInAppOnboarding,
          [
            userId,
            v,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setOpenCount(int? v) => (super.noSuchMethod(
        Invocation.method(
          #setOpenCount,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementOpenCount() => (super.noSuchMethod(
        Invocation.method(
          #incrementOpenCount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SettingsState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsState extends _i1.Mock implements _i4.SettingsState {
  MockSettingsState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SettingsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.SettingsStatus.initial,
      ) as _i4.SettingsStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  bool get enablePushNotifications => (super.noSuchMethod(
        Invocation.getter(#enablePushNotifications),
        returnValue: false,
      ) as bool);

  @override
  bool get metricHeight => (super.noSuchMethod(
        Invocation.getter(#metricHeight),
        returnValue: false,
      ) as bool);

  @override
  bool get metricTemperature => (super.noSuchMethod(
        Invocation.getter(#metricTemperature),
        returnValue: false,
      ) as bool);

  @override
  String get defaultPostVisibility => (super.noSuchMethod(
        Invocation.getter(#defaultPostVisibility),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#defaultPostVisibility),
        ),
      ) as String);

  @override
  set setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i3.AppSettings? newAppSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [newAppSettings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setEnablePushNotifications(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setEnablePushNotifications,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMetricHeight(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMetricHeight,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMetricTemperature(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMetricTemperature,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setDefaultPostVisibility(String? v) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultPostVisibility,
          [v],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PushNotificationState].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationState extends _i1.Mock
    implements _i11.PushNotificationState {
  MockPushNotificationState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> onPushSettingChanged() => (super.noSuchMethod(
        Invocation.method(
          #onPushSettingChanged,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> enablePush() => (super.noSuchMethod(
        Invocation.method(
          #enablePush,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> disablePush() => (super.noSuchMethod(
        Invocation.method(
          #disablePush,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> syncTokenIfNeeded({bool? force = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncTokenIfNeeded,
          [],
          {#force: force},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Analytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalytics extends _i1.Mock implements _i12.Analytics {
  MockAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> track(
    String? name, {
    Map<String, Object?>? props,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #track,
          [name],
          {#props: props},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> identify(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i13.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
