// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/profile/state/profile_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:two_eight_two/logging/logging.dart' as _i9;
import 'package:two_eight_two/models/models.dart' as _i2;
import 'package:two_eight_two/repos/repos.dart' as _i3;
import 'package:two_eight_two/screens/notifiers.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfile_0 extends _i1.SmartFake implements _i2.Profile {
  _FakeProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_1 extends _i1.SmartFake
    implements _i3.UserRepository {
  _FakeUserRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUserRepository_2 extends _i1.SmartFake
    implements _i3.BlockedUserRepository {
  _FakeBlockedUserRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRepository_3 extends _i1.SmartFake
    implements _i3.StorageRepository {
  _FakeStorageRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeError_4 extends _i1.SmartFake implements _i2.Error {
  _FakeError_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Profile> getProfileFromUserId({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileFromUserId,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<_i2.Profile>.value(_FakeProfile_0(
          this,
          Invocation.method(
            #getProfileFromUserId,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i4.Future<_i2.Profile>);
}

/// A class which mocks [MunroPicturesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroPicturesRepository extends _i1.Mock
    implements _i3.MunroPicturesRepository {
  MockMunroPicturesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MunroPicture>> readMunroPictures({
    required int? munroId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
    int? count = 18,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readMunroPictures,
          [],
          {
            #munroId: munroId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
            #count: count,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.MunroPicture>>.value(<_i2.MunroPicture>[]),
      ) as _i4.Future<List<_i2.MunroPicture>>);

  @override
  _i4.Future<List<_i2.MunroPicture>> readProfilePictures({
    required String? profileId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
    int? count = 18,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readProfilePictures,
          [],
          {
            #profileId: profileId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
            #count: count,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.MunroPicture>>.value(<_i2.MunroPicture>[]),
      ) as _i4.Future<List<_i2.MunroPicture>>);

  @override
  _i4.Future<void> createMunroPictures(
          {required List<_i2.MunroPicture>? munroPictures}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMunroPictures,
          [],
          {#munroPictures: munroPictures},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> deleteMunroPicturesByUrls(
          {required List<String>? imageURLs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMunroPicturesByUrls,
          [],
          {#imageURLs: imageURLs},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}

/// A class which mocks [PostsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsRepository extends _i1.Mock implements _i3.PostsRepository {
  MockPostsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> create({required _i2.Post? post}) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#post: post},
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [],
            {#post: post},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<dynamic> update({required _i2.Post? post}) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#post: post},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<_i2.Post?> readPostFromUid({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readPostFromUid,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<_i2.Post?>.value(),
      ) as _i4.Future<_i2.Post?>);

  @override
  _i4.Future<List<_i2.Post>> readPostsFromUserId({
    required String? userId,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readPostsFromUserId,
          [],
          {
            #userId: userId,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
      ) as _i4.Future<List<_i2.Post>>);

  @override
  _i4.Future<List<_i2.Post>> getFriendsFeedFromUserId({
    required String? userId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendsFeedFromUserId,
          [],
          {
            #userId: userId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
      ) as _i4.Future<List<_i2.Post>>);

  @override
  _i4.Future<List<_i2.Post>> getGlobalFeed({
    required List<String>? excludedAuthorIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalFeed,
          [],
          {
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
      ) as _i4.Future<List<_i2.Post>>);

  @override
  _i4.Future<dynamic> deletePostWithUID({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePostWithUID,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}

/// A class which mocks [UserState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserState extends _i1.Mock implements _i6.UserState {
  MockUserState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_1(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i3.UserRepository);

  @override
  _i3.BlockedUserRepository get blockedUserRepository => (super.noSuchMethod(
        Invocation.getter(#blockedUserRepository),
        returnValue: _FakeBlockedUserRepository_2(
          this,
          Invocation.getter(#blockedUserRepository),
        ),
      ) as _i3.BlockedUserRepository);

  @override
  _i3.StorageRepository get storageRepository => (super.noSuchMethod(
        Invocation.getter(#storageRepository),
        returnValue: _FakeStorageRepository_3(
          this,
          Invocation.getter(#storageRepository),
        ),
      ) as _i3.StorageRepository);

  @override
  _i6.UserStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.UserStatus.initial,
      ) as _i6.UserStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_4(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  List<String> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set setCurrentUser(_i2.AppUser? appUser) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentUser,
          appUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBlockedUsers(List<String>? blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #setBlockedUsers,
          blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> createUser({required _i2.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser({required _i2.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> readUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser({required _i2.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfileVisibility(String? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [newValue],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> updateProfile({
    required _i2.AppUser? appUser,
    _i7.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #appUser: appUser,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserLikeState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLikeState extends _i1.Mock implements _i6.UserLikeState {
  MockUserLikeState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.UserLikeStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.UserLikeStatus.initial,
      ) as _i6.UserLikeStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_4(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  Set<String> get likedPosts => (super.noSuchMethod(
        Invocation.getter(#likedPosts),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Set<String> get recentlyLikedPosts => (super.noSuchMethod(
        Invocation.getter(#recentlyLikedPosts),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Set<String> get recentlyUnlikedPosts => (super.noSuchMethod(
        Invocation.getter(#recentlyUnlikedPosts),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  set setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> likePost({
    required _i2.Post? post,
    required void Function(_i2.Post)? onPostUpdated,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #likePost,
          [],
          {
            #post: post,
            #onPostUpdated: onPostUpdated,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unLikePost({
    required _i2.Post? post,
    required void Function(_i2.Post)? onPostUpdated,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unLikePost,
          [],
          {
            #post: post,
            #onPostUpdated: onPostUpdated,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> getLikedPostIds({required List<_i2.Post>? posts}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedPostIds,
          [],
          {#posts: posts},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroCompletionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroCompletionsRepository extends _i1.Mock
    implements _i3.MunroCompletionsRepository {
  MockMunroCompletionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> create(List<_i2.MunroCompletion>? munroCompletions) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [munroCompletions],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.MunroCompletion>> getUserMunroCompletions(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserMunroCompletions,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<List<_i2.MunroCompletion>>.value(
            <_i2.MunroCompletion>[]),
      ) as _i4.Future<List<_i2.MunroCompletion>>);

  @override
  _i4.Future<List<_i2.MunroCompletion>> getMunroCompletionsFromUserList(
          {required List<String>? userIds}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMunroCompletionsFromUserList,
          [],
          {#userIds: userIds},
        ),
        returnValue: _i4.Future<List<_i2.MunroCompletion>>.value(
            <_i2.MunroCompletion>[]),
      ) as _i4.Future<List<_i2.MunroCompletion>>);

  @override
  _i4.Future<void> delete({required String? munroCompletionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#munroCompletionId: munroCompletionId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteByMunroIdsAndPostId({
    required List<int>? munroIds,
    required String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteByMunroIdsAndPostId,
          [],
          {
            #munroIds: munroIds,
            #postId: postId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i9.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
