import 'package:firebase_auth/firebase_auth.dart';
import 'package:two_eight_two/models/munro_challenge_model.dart';

class AppUser {
  final String? uid;
  String? displayName;
  String? searchName;
  String? firstName;
  String? lastName;
  String? profilePictureURL;
  int? followersCount;
  int? followingCount;
  String? bio;
  String? fcmToken;

  final List<Map<String, dynamic>>? personalMunroData;
  final List<MunroChallenge> munroChallenges;

  AppUser({
    this.uid,
    this.displayName,
    this.searchName,
    this.firstName,
    this.lastName,
    this.profilePictureURL,
    this.followersCount,
    this.followingCount,
    this.bio,
    this.fcmToken,
    this.personalMunroData = personalMunroDataExample,
    this.munroChallenges = const [],
  });

  Map<String, dynamic> toJSON() {
    return <String, dynamic>{
      AppUserFields.uid: uid,
      AppUserFields.displayName: displayName,
      AppUserFields.searchName: searchName,
      AppUserFields.firstName: firstName,
      AppUserFields.lastName: lastName,
      AppUserFields.profilePictureURL: profilePictureURL,
      AppUserFields.followersCount: followersCount,
      AppUserFields.followingCount: followingCount,
      AppUserFields.bio: bio,
      AppUserFields.fcmToken: fcmToken,
      AppUserFields.personalMunroData: personalMunroData,
      AppUserFields.munroChallenges: munroChallenges.map((e) => e.toJSON()).toList(),
    };
  }

  static AppUser fromJSON(Map<String, dynamic> json) {
    List<dynamic> personalMunroData = json[AppUserFields.personalMunroData];
    List<Map<String, dynamic>> listPersonalMunroData = List<Map<String, dynamic>>.from(personalMunroData);

    List<dynamic> munroChallenges = json[AppUserFields.munroChallenges];
    List<MunroChallenge> listMunroChallenges = munroChallenges.map((e) => MunroChallenge.fromJSON(e)).toList();

    return AppUser(
      uid: json[AppUserFields.uid] as String?,
      displayName: json[AppUserFields.displayName] as String?,
      searchName: json[AppUserFields.searchName] as String?,
      firstName: json[AppUserFields.firstName] as String?,
      lastName: json[AppUserFields.lastName] as String?,
      profilePictureURL: json[AppUserFields.profilePictureURL] as String?,
      followersCount: json[AppUserFields.followersCount] as int? ?? 0,
      followingCount: json[AppUserFields.followingCount] as int? ?? 0,
      bio: json[AppUserFields.bio] as String?,
      fcmToken: json[AppUserFields.fcmToken] as String?,
      personalMunroData: listPersonalMunroData,
      munroChallenges: listMunroChallenges,
    );
  }

  AppUser copyWith({
    String? uid,
    String? displayName,
    String? searchName,
    String? firstName,
    String? lastName,
    String? profilePictureURL,
    int? followersCount,
    int? followingCount,
    String? bio,
    String? fcmToken,
    List<Map<String, dynamic>>? personalMunroData,
    List<MunroChallenge>? munroChallenges,
  }) {
    return AppUser(
      uid: uid ?? this.uid,
      displayName: displayName ?? this.displayName,
      searchName: searchName ?? this.searchName,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      profilePictureURL: profilePictureURL ?? this.profilePictureURL,
      followersCount: followersCount ?? this.followersCount,
      followingCount: followingCount ?? this.followingCount,
      bio: bio ?? this.bio,
      fcmToken: fcmToken ?? this.fcmToken,
      personalMunroData: personalMunroData ?? this.personalMunroData,
      munroChallenges: munroChallenges ?? this.munroChallenges,
    );
  }

  // From firebase
  static AppUser? appUserFromFirebaseUser(User? firebaseUser) {
    if (firebaseUser == null) return null;

    return AppUser(uid: firebaseUser.uid);
  }

  @override
  String toString() => '''AppUser(
      ${AppUserFields.uid}: $uid,
      ${AppUserFields.displayName}: $displayName,
      ${AppUserFields.searchName}: $searchName,
      ${AppUserFields.firstName}: $firstName,
      ${AppUserFields.lastName}: $lastName,
      ${AppUserFields.profilePictureURL}: $profilePictureURL,
      ${AppUserFields.followingCount}: $followersCount,
      ${AppUserFields.followersCount}: $followersCount,
      ${AppUserFields.personalMunroData}: $personalMunroData, 
      ${AppUserFields.bio}: $bio,
      ${AppUserFields.fcmToken}:$fcmToken
      )''';
}

class AppUserFields {
  static String uid = 'uid';
  static String displayName = 'displayName';
  static String searchName = 'searchName';
  static String firstName = 'firstName';
  static String lastName = 'lastName';
  static String profilePictureURL = 'profilePictureURL';
  static String personalMunroData = 'personalMunroData';
  static String followingCount = 'followingCount';
  static String followersCount = 'followersCount';
  static String bio = 'bio';
  static String fcmToken = 'fcmToken';
  static String munroChallenges = 'munroChallenges';
}

const List<Map<String, dynamic>> personalMunroDataExample = [
  {"id": 1, "summited": false, "summitedDate": null, "saved": false},
  {"id": 2, "summited": false, "summitedDate": null, "saved": false},
  {"id": 3, "summited": false, "summitedDate": null, "saved": false},
  {"id": 4, "summited": false, "summitedDate": null, "saved": false},
  {"id": 5, "summited": false, "summitedDate": null, "saved": false},
  {"id": 6, "summited": false, "summitedDate": null, "saved": false},
  {"id": 7, "summited": false, "summitedDate": null, "saved": false},
  {"id": 8, "summited": false, "summitedDate": null, "saved": false},
  {"id": 9, "summited": false, "summitedDate": null, "saved": false},
  {"id": 10, "summited": false, "summitedDate": null, "saved": false},
  {"id": 11, "summited": false, "summitedDate": null, "saved": false},
  {"id": 12, "summited": false, "summitedDate": null, "saved": false},
  {"id": 13, "summited": false, "summitedDate": null, "saved": false},
  {"id": 14, "summited": false, "summitedDate": null, "saved": false},
  {"id": 15, "summited": false, "summitedDate": null, "saved": false},
  {"id": 16, "summited": false, "summitedDate": null, "saved": false},
  {"id": 17, "summited": false, "summitedDate": null, "saved": false},
  {"id": 18, "summited": false, "summitedDate": null, "saved": false},
  {"id": 19, "summited": false, "summitedDate": null, "saved": false},
  {"id": 20, "summited": false, "summitedDate": null, "saved": false},
  {"id": 21, "summited": false, "summitedDate": null, "saved": false},
  {"id": 22, "summited": false, "summitedDate": null, "saved": false},
  {"id": 23, "summited": false, "summitedDate": null, "saved": false},
  {"id": 24, "summited": false, "summitedDate": null, "saved": false},
  {"id": 25, "summited": false, "summitedDate": null, "saved": false},
  {"id": 26, "summited": false, "summitedDate": null, "saved": false},
  {"id": 27, "summited": false, "summitedDate": null, "saved": false},
  {"id": 28, "summited": false, "summitedDate": null, "saved": false},
  {"id": 29, "summited": false, "summitedDate": null, "saved": false},
  {"id": 30, "summited": false, "summitedDate": null, "saved": false},
  {"id": 31, "summited": false, "summitedDate": null, "saved": false},
  {"id": 32, "summited": false, "summitedDate": null, "saved": false},
  {"id": 33, "summited": false, "summitedDate": null, "saved": false},
  {"id": 34, "summited": false, "summitedDate": null, "saved": false},
  {"id": 35, "summited": false, "summitedDate": null, "saved": false},
  {"id": 36, "summited": false, "summitedDate": null, "saved": false},
  {"id": 37, "summited": false, "summitedDate": null, "saved": false},
  {"id": 38, "summited": false, "summitedDate": null, "saved": false},
  {"id": 39, "summited": false, "summitedDate": null, "saved": false},
  {"id": 40, "summited": false, "summitedDate": null, "saved": false},
  {"id": 41, "summited": false, "summitedDate": null, "saved": false},
  {"id": 42, "summited": false, "summitedDate": null, "saved": false},
  {"id": 43, "summited": false, "summitedDate": null, "saved": false},
  {"id": 44, "summited": false, "summitedDate": null, "saved": false},
  {"id": 45, "summited": false, "summitedDate": null, "saved": false},
  {"id": 46, "summited": false, "summitedDate": null, "saved": false},
  {"id": 47, "summited": false, "summitedDate": null, "saved": false},
  {"id": 48, "summited": false, "summitedDate": null, "saved": false},
  {"id": 49, "summited": false, "summitedDate": null, "saved": false},
  {"id": 50, "summited": false, "summitedDate": null, "saved": false},
  {"id": 51, "summited": false, "summitedDate": null, "saved": false},
  {"id": 52, "summited": false, "summitedDate": null, "saved": false},
  {"id": 53, "summited": false, "summitedDate": null, "saved": false},
  {"id": 54, "summited": false, "summitedDate": null, "saved": false},
  {"id": 55, "summited": false, "summitedDate": null, "saved": false},
  {"id": 56, "summited": false, "summitedDate": null, "saved": false},
  {"id": 57, "summited": false, "summitedDate": null, "saved": false},
  {"id": 58, "summited": false, "summitedDate": null, "saved": false},
  {"id": 59, "summited": false, "summitedDate": null, "saved": false},
  {"id": 60, "summited": false, "summitedDate": null, "saved": false},
  {"id": 61, "summited": false, "summitedDate": null, "saved": false},
  {"id": 62, "summited": false, "summitedDate": null, "saved": false},
  {"id": 63, "summited": false, "summitedDate": null, "saved": false},
  {"id": 64, "summited": false, "summitedDate": null, "saved": false},
  {"id": 65, "summited": false, "summitedDate": null, "saved": false},
  {"id": 66, "summited": false, "summitedDate": null, "saved": false},
  {"id": 67, "summited": false, "summitedDate": null, "saved": false},
  {"id": 68, "summited": false, "summitedDate": null, "saved": false},
  {"id": 69, "summited": false, "summitedDate": null, "saved": false},
  {"id": 70, "summited": false, "summitedDate": null, "saved": false},
  {"id": 71, "summited": false, "summitedDate": null, "saved": false},
  {"id": 72, "summited": false, "summitedDate": null, "saved": false},
  {"id": 73, "summited": false, "summitedDate": null, "saved": false},
  {"id": 74, "summited": false, "summitedDate": null, "saved": false},
  {"id": 75, "summited": false, "summitedDate": null, "saved": false},
  {"id": 76, "summited": false, "summitedDate": null, "saved": false},
  {"id": 77, "summited": false, "summitedDate": null, "saved": false},
  {"id": 78, "summited": false, "summitedDate": null, "saved": false},
  {"id": 79, "summited": false, "summitedDate": null, "saved": false},
  {"id": 80, "summited": false, "summitedDate": null, "saved": false},
  {"id": 81, "summited": false, "summitedDate": null, "saved": false},
  {"id": 82, "summited": false, "summitedDate": null, "saved": false},
  {"id": 83, "summited": false, "summitedDate": null, "saved": false},
  {"id": 84, "summited": false, "summitedDate": null, "saved": false},
  {"id": 85, "summited": false, "summitedDate": null, "saved": false},
  {"id": 86, "summited": false, "summitedDate": null, "saved": false},
  {"id": 87, "summited": false, "summitedDate": null, "saved": false},
  {"id": 88, "summited": false, "summitedDate": null, "saved": false},
  {"id": 89, "summited": false, "summitedDate": null, "saved": false},
  {"id": 90, "summited": false, "summitedDate": null, "saved": false},
  {"id": 91, "summited": false, "summitedDate": null, "saved": false},
  {"id": 92, "summited": false, "summitedDate": null, "saved": false},
  {"id": 93, "summited": false, "summitedDate": null, "saved": false},
  {"id": 94, "summited": false, "summitedDate": null, "saved": false},
  {"id": 95, "summited": false, "summitedDate": null, "saved": false},
  {"id": 96, "summited": false, "summitedDate": null, "saved": false},
  {"id": 97, "summited": false, "summitedDate": null, "saved": false},
  {"id": 98, "summited": false, "summitedDate": null, "saved": false},
  {"id": 99, "summited": false, "summitedDate": null, "saved": false},
  {"id": 100, "summited": false, "summitedDate": null, "saved": false},
  {"id": 101, "summited": false, "summitedDate": null, "saved": false},
  {"id": 102, "summited": false, "summitedDate": null, "saved": false},
  {"id": 103, "summited": false, "summitedDate": null, "saved": false},
  {"id": 104, "summited": false, "summitedDate": null, "saved": false},
  {"id": 105, "summited": false, "summitedDate": null, "saved": false},
  {"id": 106, "summited": false, "summitedDate": null, "saved": false},
  {"id": 107, "summited": false, "summitedDate": null, "saved": false},
  {"id": 108, "summited": false, "summitedDate": null, "saved": false},
  {"id": 109, "summited": false, "summitedDate": null, "saved": false},
  {"id": 110, "summited": false, "summitedDate": null, "saved": false},
  {"id": 111, "summited": false, "summitedDate": null, "saved": false},
  {"id": 112, "summited": false, "summitedDate": null, "saved": false},
  {"id": 113, "summited": false, "summitedDate": null, "saved": false},
  {"id": 114, "summited": false, "summitedDate": null, "saved": false},
  {"id": 115, "summited": false, "summitedDate": null, "saved": false},
  {"id": 116, "summited": false, "summitedDate": null, "saved": false},
  {"id": 117, "summited": false, "summitedDate": null, "saved": false},
  {"id": 118, "summited": false, "summitedDate": null, "saved": false},
  {"id": 119, "summited": false, "summitedDate": null, "saved": false},
  {"id": 120, "summited": false, "summitedDate": null, "saved": false},
  {"id": 121, "summited": false, "summitedDate": null, "saved": false},
  {"id": 122, "summited": false, "summitedDate": null, "saved": false},
  {"id": 123, "summited": false, "summitedDate": null, "saved": false},
  {"id": 124, "summited": false, "summitedDate": null, "saved": false},
  {"id": 125, "summited": false, "summitedDate": null, "saved": false},
  {"id": 126, "summited": false, "summitedDate": null, "saved": false},
  {"id": 127, "summited": false, "summitedDate": null, "saved": false},
  {"id": 128, "summited": false, "summitedDate": null, "saved": false},
  {"id": 129, "summited": false, "summitedDate": null, "saved": false},
  {"id": 130, "summited": false, "summitedDate": null, "saved": false},
  {"id": 131, "summited": false, "summitedDate": null, "saved": false},
  {"id": 132, "summited": false, "summitedDate": null, "saved": false},
  {"id": 133, "summited": false, "summitedDate": null, "saved": false},
  {"id": 134, "summited": false, "summitedDate": null, "saved": false},
  {"id": 135, "summited": false, "summitedDate": null, "saved": false},
  {"id": 136, "summited": false, "summitedDate": null, "saved": false},
  {"id": 137, "summited": false, "summitedDate": null, "saved": false},
  {"id": 138, "summited": false, "summitedDate": null, "saved": false},
  {"id": 139, "summited": false, "summitedDate": null, "saved": false},
  {"id": 140, "summited": false, "summitedDate": null, "saved": false},
  {"id": 141, "summited": false, "summitedDate": null, "saved": false},
  {"id": 142, "summited": false, "summitedDate": null, "saved": false},
  {"id": 143, "summited": false, "summitedDate": null, "saved": false},
  {"id": 144, "summited": false, "summitedDate": null, "saved": false},
  {"id": 145, "summited": false, "summitedDate": null, "saved": false},
  {"id": 146, "summited": false, "summitedDate": null, "saved": false},
  {"id": 147, "summited": false, "summitedDate": null, "saved": false},
  {"id": 148, "summited": false, "summitedDate": null, "saved": false},
  {"id": 149, "summited": false, "summitedDate": null, "saved": false},
  {"id": 150, "summited": false, "summitedDate": null, "saved": false},
  {"id": 151, "summited": false, "summitedDate": null, "saved": false},
  {"id": 152, "summited": false, "summitedDate": null, "saved": false},
  {"id": 153, "summited": false, "summitedDate": null, "saved": false},
  {"id": 154, "summited": false, "summitedDate": null, "saved": false},
  {"id": 155, "summited": false, "summitedDate": null, "saved": false},
  {"id": 156, "summited": false, "summitedDate": null, "saved": false},
  {"id": 157, "summited": false, "summitedDate": null, "saved": false},
  {"id": 158, "summited": false, "summitedDate": null, "saved": false},
  {"id": 159, "summited": false, "summitedDate": null, "saved": false},
  {"id": 160, "summited": false, "summitedDate": null, "saved": false},
  {"id": 161, "summited": false, "summitedDate": null, "saved": false},
  {"id": 162, "summited": false, "summitedDate": null, "saved": false},
  {"id": 163, "summited": false, "summitedDate": null, "saved": false},
  {"id": 164, "summited": false, "summitedDate": null, "saved": false},
  {"id": 165, "summited": false, "summitedDate": null, "saved": false},
  {"id": 166, "summited": false, "summitedDate": null, "saved": false},
  {"id": 167, "summited": false, "summitedDate": null, "saved": false},
  {"id": 168, "summited": false, "summitedDate": null, "saved": false},
  {"id": 169, "summited": false, "summitedDate": null, "saved": false},
  {"id": 170, "summited": false, "summitedDate": null, "saved": false},
  {"id": 171, "summited": false, "summitedDate": null, "saved": false},
  {"id": 172, "summited": false, "summitedDate": null, "saved": false},
  {"id": 173, "summited": false, "summitedDate": null, "saved": false},
  {"id": 174, "summited": false, "summitedDate": null, "saved": false},
  {"id": 175, "summited": false, "summitedDate": null, "saved": false},
  {"id": 176, "summited": false, "summitedDate": null, "saved": false},
  {"id": 177, "summited": false, "summitedDate": null, "saved": false},
  {"id": 178, "summited": false, "summitedDate": null, "saved": false},
  {"id": 179, "summited": false, "summitedDate": null, "saved": false},
  {"id": 180, "summited": false, "summitedDate": null, "saved": false},
  {"id": 181, "summited": false, "summitedDate": null, "saved": false},
  {"id": 182, "summited": false, "summitedDate": null, "saved": false},
  {"id": 183, "summited": false, "summitedDate": null, "saved": false},
  {"id": 184, "summited": false, "summitedDate": null, "saved": false},
  {"id": 185, "summited": false, "summitedDate": null, "saved": false},
  {"id": 186, "summited": false, "summitedDate": null, "saved": false},
  {"id": 187, "summited": false, "summitedDate": null, "saved": false},
  {"id": 188, "summited": false, "summitedDate": null, "saved": false},
  {"id": 189, "summited": false, "summitedDate": null, "saved": false},
  {"id": 190, "summited": false, "summitedDate": null, "saved": false},
  {"id": 191, "summited": false, "summitedDate": null, "saved": false},
  {"id": 192, "summited": false, "summitedDate": null, "saved": false},
  {"id": 193, "summited": false, "summitedDate": null, "saved": false},
  {"id": 194, "summited": false, "summitedDate": null, "saved": false},
  {"id": 195, "summited": false, "summitedDate": null, "saved": false},
  {"id": 196, "summited": false, "summitedDate": null, "saved": false},
  {"id": 197, "summited": false, "summitedDate": null, "saved": false},
  {"id": 198, "summited": false, "summitedDate": null, "saved": false},
  {"id": 199, "summited": false, "summitedDate": null, "saved": false},
  {"id": 200, "summited": false, "summitedDate": null, "saved": false},
  {"id": 201, "summited": false, "summitedDate": null, "saved": false},
  {"id": 202, "summited": false, "summitedDate": null, "saved": false},
  {"id": 203, "summited": false, "summitedDate": null, "saved": false},
  {"id": 204, "summited": false, "summitedDate": null, "saved": false},
  {"id": 205, "summited": false, "summitedDate": null, "saved": false},
  {"id": 206, "summited": false, "summitedDate": null, "saved": false},
  {"id": 207, "summited": false, "summitedDate": null, "saved": false},
  {"id": 208, "summited": false, "summitedDate": null, "saved": false},
  {"id": 209, "summited": false, "summitedDate": null, "saved": false},
  {"id": 210, "summited": false, "summitedDate": null, "saved": false},
  {"id": 211, "summited": false, "summitedDate": null, "saved": false},
  {"id": 212, "summited": false, "summitedDate": null, "saved": false},
  {"id": 213, "summited": false, "summitedDate": null, "saved": false},
  {"id": 214, "summited": false, "summitedDate": null, "saved": false},
  {"id": 215, "summited": false, "summitedDate": null, "saved": false},
  {"id": 216, "summited": false, "summitedDate": null, "saved": false},
  {"id": 217, "summited": false, "summitedDate": null, "saved": false},
  {"id": 218, "summited": false, "summitedDate": null, "saved": false},
  {"id": 219, "summited": false, "summitedDate": null, "saved": false},
  {"id": 220, "summited": false, "summitedDate": null, "saved": false},
  {"id": 221, "summited": false, "summitedDate": null, "saved": false},
  {"id": 222, "summited": false, "summitedDate": null, "saved": false},
  {"id": 223, "summited": false, "summitedDate": null, "saved": false},
  {"id": 224, "summited": false, "summitedDate": null, "saved": false},
  {"id": 225, "summited": false, "summitedDate": null, "saved": false},
  {"id": 226, "summited": false, "summitedDate": null, "saved": false},
  {"id": 227, "summited": false, "summitedDate": null, "saved": false},
  {"id": 228, "summited": false, "summitedDate": null, "saved": false},
  {"id": 229, "summited": false, "summitedDate": null, "saved": false},
  {"id": 230, "summited": false, "summitedDate": null, "saved": false},
  {"id": 231, "summited": false, "summitedDate": null, "saved": false},
  {"id": 232, "summited": false, "summitedDate": null, "saved": false},
  {"id": 233, "summited": false, "summitedDate": null, "saved": false},
  {"id": 234, "summited": false, "summitedDate": null, "saved": false},
  {"id": 235, "summited": false, "summitedDate": null, "saved": false},
  {"id": 236, "summited": false, "summitedDate": null, "saved": false},
  {"id": 237, "summited": false, "summitedDate": null, "saved": false},
  {"id": 238, "summited": false, "summitedDate": null, "saved": false},
  {"id": 239, "summited": false, "summitedDate": null, "saved": false},
  {"id": 240, "summited": false, "summitedDate": null, "saved": false},
  {"id": 241, "summited": false, "summitedDate": null, "saved": false},
  {"id": 242, "summited": false, "summitedDate": null, "saved": false},
  {"id": 243, "summited": false, "summitedDate": null, "saved": false},
  {"id": 244, "summited": false, "summitedDate": null, "saved": false},
  {"id": 245, "summited": false, "summitedDate": null, "saved": false},
  {"id": 246, "summited": false, "summitedDate": null, "saved": false},
  {"id": 247, "summited": false, "summitedDate": null, "saved": false},
  {"id": 248, "summited": false, "summitedDate": null, "saved": false},
  {"id": 249, "summited": false, "summitedDate": null, "saved": false},
  {"id": 250, "summited": false, "summitedDate": null, "saved": false},
  {"id": 251, "summited": false, "summitedDate": null, "saved": false},
  {"id": 252, "summited": false, "summitedDate": null, "saved": false},
  {"id": 253, "summited": false, "summitedDate": null, "saved": false},
  {"id": 254, "summited": false, "summitedDate": null, "saved": false},
  {"id": 255, "summited": false, "summitedDate": null, "saved": false},
  {"id": 256, "summited": false, "summitedDate": null, "saved": false},
  {"id": 257, "summited": false, "summitedDate": null, "saved": false},
  {"id": 258, "summited": false, "summitedDate": null, "saved": false},
  {"id": 259, "summited": false, "summitedDate": null, "saved": false},
  {"id": 260, "summited": false, "summitedDate": null, "saved": false},
  {"id": 261, "summited": false, "summitedDate": null, "saved": false},
  {"id": 262, "summited": false, "summitedDate": null, "saved": false},
  {"id": 263, "summited": false, "summitedDate": null, "saved": false},
  {"id": 264, "summited": false, "summitedDate": null, "saved": false},
  {"id": 265, "summited": false, "summitedDate": null, "saved": false},
  {"id": 266, "summited": false, "summitedDate": null, "saved": false},
  {"id": 267, "summited": false, "summitedDate": null, "saved": false},
  {"id": 268, "summited": false, "summitedDate": null, "saved": false},
  {"id": 269, "summited": false, "summitedDate": null, "saved": false},
  {"id": 270, "summited": false, "summitedDate": null, "saved": false},
  {"id": 271, "summited": false, "summitedDate": null, "saved": false},
  {"id": 272, "summited": false, "summitedDate": null, "saved": false},
  {"id": 273, "summited": false, "summitedDate": null, "saved": false},
  {"id": 274, "summited": false, "summitedDate": null, "saved": false},
  {"id": 275, "summited": false, "summitedDate": null, "saved": false},
  {"id": 276, "summited": false, "summitedDate": null, "saved": false},
  {"id": 277, "summited": false, "summitedDate": null, "saved": false},
  {"id": 278, "summited": false, "summitedDate": null, "saved": false},
  {"id": 279, "summited": false, "summitedDate": null, "saved": false},
  {"id": 280, "summited": false, "summitedDate": null, "saved": false},
  {"id": 281, "summited": false, "summitedDate": null, "saved": false},
  {"id": 282, "summited": false, "summitedDate": null, "saved": false},
];
