// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/auth/state/user_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:two_eight_two/models/models.dart' as _i4;
import 'package:two_eight_two/repos/blocked_user_repository.dart' as _i5;
import 'package:two_eight_two/repos/user_repository.dart' as _i2;
import 'package:two_eight_two/services/storage_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> create({required _i4.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update({required _i4.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<dynamic> deleteUserWithUID({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserWithUID,
          [],
          {#uid: uid},
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i4.AppUser?> readUserFromUid({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readUserFromUid,
          [],
          {#uid: uid},
        ),
        returnValue: _i3.Future<_i4.AppUser?>.value(),
      ) as _i3.Future<_i4.AppUser?>);

  @override
  _i3.Future<List<_i4.AppUser>> readUsersByName({
    required String? searchTerm,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readUsersByName,
          [],
          {
            #searchTerm: searchTerm,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.AppUser>>.value(<_i4.AppUser>[]),
      ) as _i3.Future<List<_i4.AppUser>>);

  @override
  _i3.Future<List<_i4.AppUser>> readUsersFromUids(
          {required List<String>? uids}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readUsersFromUids,
          [],
          {#uids: uids},
        ),
        returnValue: _i3.Future<List<_i4.AppUser>>.value(<_i4.AppUser>[]),
      ) as _i3.Future<List<_i4.AppUser>>);
}

/// A class which mocks [BlockedUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockedUserRepository extends _i1.Mock
    implements _i5.BlockedUserRepository {
  MockBlockedUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> blockUser(
          {required _i4.BlockedUserRelationship? blockedUserRelationship}) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#blockedUserRelationship: blockedUserRelationship},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getBlockedUsersForUid({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlockedUsersForUid,
          [],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }
}
