// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/weather/state/weather_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:two_eight_two/enums/enums.dart' as _i9;
import 'package:two_eight_two/logging/logging.dart' as _i11;
import 'package:two_eight_two/models/models.dart' as _i2;
import 'package:two_eight_two/repos/repos.dart' as _i3;
import 'package:two_eight_two/screens/explore/state/munro_state.dart' as _i8;
import 'package:two_eight_two/screens/settings/state/settings_state.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeError_0 extends _i1.SmartFake implements _i2.Error {
  _FakeError_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroRepository_1 extends _i1.SmartFake
    implements _i3.MunroRepository {
  _FakeMunroRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilterOptions_2 extends _i1.SmartFake implements _i2.FilterOptions {
  _FakeFilterOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeartherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeartherRepository extends _i1.Mock
    implements _i3.WeartherRepository {
  MockWeartherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Weather>> fetchWeather({
    required double? lat,
    required double? lon,
    required String? metric,
    required String? apiKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWeather,
          [],
          {
            #lat: lat,
            #lon: lon,
            #metric: metric,
            #apiKey: apiKey,
          },
        ),
        returnValue: _i4.Future<List<_i2.Weather>>.value(<_i2.Weather>[]),
      ) as _i4.Future<List<_i2.Weather>>);
}

/// A class which mocks [SettingsState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsState extends _i1.Mock implements _i5.SettingsState {
  MockSettingsState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SettingsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.SettingsStatus.initial,
      ) as _i5.SettingsStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  bool get enablePushNotifications => (super.noSuchMethod(
        Invocation.getter(#enablePushNotifications),
        returnValue: false,
      ) as bool);

  @override
  bool get metricHeight => (super.noSuchMethod(
        Invocation.getter(#metricHeight),
        returnValue: false,
      ) as bool);

  @override
  bool get metricTemperature => (super.noSuchMethod(
        Invocation.getter(#metricTemperature),
        returnValue: false,
      ) as bool);

  @override
  String get defaultPostVisibility => (super.noSuchMethod(
        Invocation.getter(#defaultPostVisibility),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#defaultPostVisibility),
        ),
      ) as String);

  @override
  set setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(_i2.AppSettings? newAppSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [newAppSettings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setEnablePushNotifications(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setEnablePushNotifications,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setMetricHeight(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMetricHeight,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setMetricTemperature(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMetricTemperature,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setDefaultPostVisibility(String? v) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultPostVisibility,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroState extends _i1.Mock implements _i8.MunroState {
  MockMunroState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MunroRepository get munroRepository => (super.noSuchMethod(
        Invocation.getter(#munroRepository),
        returnValue: _FakeMunroRepository_1(
          this,
          Invocation.getter(#munroRepository),
        ),
      ) as _i3.MunroRepository);

  @override
  _i8.MunroStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i8.MunroStatus.initial,
      ) as _i8.MunroStatus);

  @override
  _i2.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.Error);

  @override
  List<_i2.Munro> get munroList => (super.noSuchMethod(
        Invocation.getter(#munroList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  List<_i2.Munro> get filteredMunroList => (super.noSuchMethod(
        Invocation.getter(#filteredMunroList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  _i9.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i9.SortOrder.alphabetical,
      ) as _i9.SortOrder);

  @override
  _i2.FilterOptions get filterOptions => (super.noSuchMethod(
        Invocation.getter(#filterOptions),
        returnValue: _FakeFilterOptions_2(
          this,
          Invocation.getter(#filterOptions),
        ),
      ) as _i2.FilterOptions);

  @override
  bool get isFilterOptionsSet => (super.noSuchMethod(
        Invocation.getter(#isFilterOptionsSet),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.Munro> get createPostFilteredMunroList => (super.noSuchMethod(
        Invocation.getter(#createPostFilteredMunroList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  List<_i2.Munro> get bulkMunroUpdateList => (super.noSuchMethod(
        Invocation.getter(#bulkMunroUpdateList),
        returnValue: <_i2.Munro>[],
      ) as List<_i2.Munro>);

  @override
  set setStatus(_i8.MunroStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i2.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setMunroList(List<_i2.Munro>? munroList) => super.noSuchMethod(
        Invocation.setter(
          #setMunroList,
          munroList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunroId(int? selectedMunroId) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunroId,
          selectedMunroId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setLatLngBounds(_i10.LatLngBounds? bounds) => super.noSuchMethod(
        Invocation.setter(
          #setLatLngBounds,
          bounds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSortOrder(_i9.SortOrder? sortOrder) => super.noSuchMethod(
        Invocation.setter(
          #setSortOrder,
          sortOrder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterOptions(_i2.FilterOptions? filterOptions) => super.noSuchMethod(
        Invocation.setter(
          #setFilterOptions,
          filterOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setGroupFilterMunroIds(List<int>? groupFilterMunroIds) =>
      super.noSuchMethod(
        Invocation.setter(
          #setGroupFilterMunroIds,
          groupFilterMunroIds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setCreatePostFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setCreatePostFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBulkMunroUpdateFilterString(String? filterString) =>
      super.noSuchMethod(
        Invocation.setter(
          #setBulkMunroUpdateFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadMunros() => (super.noSuchMethod(
        Invocation.method(
          #loadMunros,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void syncCompletedIds(Set<int>? ids) => super.noSuchMethod(
        Invocation.method(
          #syncCompletedIds,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilterAndSorting() => super.noSuchMethod(
        Invocation.method(
          #clearFilterAndSorting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
