// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/onboarding/state/onboarding_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:two_eight_two/analytics/analytics_base.dart' as _i7;
import 'package:two_eight_two/logging/logger.dart' as _i8;
import 'package:two_eight_two/models/models.dart' as _i2;
import 'package:two_eight_two/repos/app_flags_repository.dart' as _i5;
import 'package:two_eight_two/repos/onboarding_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOnboardingTotals_0 extends _i1.SmartFake
    implements _i2.OnboardingTotals {
  _FakeOnboardingTotals_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnboardingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingRepository extends _i1.Mock
    implements _i3.OnboardingRepository {
  MockOnboardingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.OnboardingFeedPost>> fetchFeedPosts() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFeedPosts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.OnboardingFeedPost>>.value(
            <_i2.OnboardingFeedPost>[]),
      ) as _i4.Future<List<_i2.OnboardingFeedPost>>);

  @override
  _i4.Future<_i2.OnboardingTotals> fetchTotals() => (super.noSuchMethod(
        Invocation.method(
          #fetchTotals,
          [],
        ),
        returnValue:
            _i4.Future<_i2.OnboardingTotals>.value(_FakeOnboardingTotals_0(
          this,
          Invocation.method(
            #fetchTotals,
            [],
          ),
        )),
      ) as _i4.Future<_i2.OnboardingTotals>);

  @override
  _i4.Future<List<_i2.OnboardingAchievements>> fetchAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAchievements,
          [],
        ),
        returnValue: _i4.Future<List<_i2.OnboardingAchievements>>.value(
            <_i2.OnboardingAchievements>[]),
      ) as _i4.Future<List<_i2.OnboardingAchievements>>);
}

/// A class which mocks [AppFlagsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFlagsRepository extends _i1.Mock
    implements _i5.AppFlagsRepository {
  MockAppFlagsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get onboardingCompleted => (super.noSuchMethod(
        Invocation.getter(#onboardingCompleted),
        returnValue: false,
      ) as bool);

  @override
  bool get mapTerrain => (super.noSuchMethod(
        Invocation.getter(#mapTerrain),
        returnValue: false,
      ) as bool);

  @override
  bool get showBulkMunroDialog => (super.noSuchMethod(
        Invocation.getter(#showBulkMunroDialog),
        returnValue: false,
      ) as bool);

  @override
  int get lastFeedbackSurveyNumber => (super.noSuchMethod(
        Invocation.getter(#lastFeedbackSurveyNumber),
        returnValue: 0,
      ) as int);

  @override
  String get lastAppUpdateDialogDate => (super.noSuchMethod(
        Invocation.getter(#lastAppUpdateDialogDate),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#lastAppUpdateDialogDate),
        ),
      ) as String);

  @override
  int get openCount => (super.noSuchMethod(
        Invocation.getter(#openCount),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> setOnboardingCompleted(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setOnboardingCompleted,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setMapTerrain(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setMapTerrain,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setShowBulkMunroDialog(bool? v) => (super.noSuchMethod(
        Invocation.method(
          #setShowBulkMunroDialog,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLastFeedbackSurveyNumber(int? v) => (super.noSuchMethod(
        Invocation.method(
          #setLastFeedbackSurveyNumber,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLastAppUpdateDialogDate(String? isoDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastAppUpdateDialogDate,
          [isoDate],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool showWhatsNewDialog(String? version) => (super.noSuchMethod(
        Invocation.method(
          #showWhatsNewDialog,
          [version],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setShownWhatsNewDialog(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShownWhatsNewDialog,
          [version],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setFirstAppVersion(String? v) => (super.noSuchMethod(
        Invocation.method(
          #setFirstAppVersion,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool showInAppOnboarding(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #showInAppOnboarding,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setShowInAppOnboarding(
    String? userId,
    bool? v,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowInAppOnboarding,
          [
            userId,
            v,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOpenCount(int? v) => (super.noSuchMethod(
        Invocation.method(
          #setOpenCount,
          [v],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> incrementOpenCount() => (super.noSuchMethod(
        Invocation.method(
          #incrementOpenCount,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Analytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalytics extends _i1.Mock implements _i7.Analytics {
  MockAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> track(
    String? name, {
    Map<String, Object?>? props,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #track,
          [name],
          {#props: props},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> identify(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i8.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
