// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/create_review/state/create_review_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:two_eight_two/enums/enums.dart' as _i9;
import 'package:two_eight_two/logging/logging.dart' as _i11;
import 'package:two_eight_two/models/models.dart' as _i3;
import 'package:two_eight_two/repos/repos.dart' as _i2;
import 'package:two_eight_two/screens/auth/state/user_state.dart' as _i5;
import 'package:two_eight_two/screens/explore/state/munro_state.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUserRepository_1 extends _i1.SmartFake
    implements _i2.BlockedUserRepository {
  _FakeBlockedUserRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRepository_2 extends _i1.SmartFake
    implements _i2.StorageRepository {
  _FakeStorageRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeError_3 extends _i1.SmartFake implements _i3.Error {
  _FakeError_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroRepository_4 extends _i1.SmartFake
    implements _i2.MunroRepository {
  _FakeMunroRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilterOptions_5 extends _i1.SmartFake implements _i3.FilterOptions {
  _FakeFilterOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReviewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewsRepository extends _i1.Mock implements _i2.ReviewsRepository {
  MockReviewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> create({required _i3.Review? review}) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#review: review},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update({required _i3.Review? review}) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#review: review},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.Review>> readReviewsFromMunro({
    required int? munroId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readReviewsFromMunro,
          [],
          {
            #munroId: munroId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i3.Review>>.value(<_i3.Review>[]),
      ) as _i4.Future<List<_i3.Review>>);

  @override
  _i4.Future<void> delete({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UserState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserState extends _i1.Mock implements _i5.UserState {
  MockUserState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);

  @override
  _i2.BlockedUserRepository get blockedUserRepository => (super.noSuchMethod(
        Invocation.getter(#blockedUserRepository),
        returnValue: _FakeBlockedUserRepository_1(
          this,
          Invocation.getter(#blockedUserRepository),
        ),
      ) as _i2.BlockedUserRepository);

  @override
  _i2.StorageRepository get storageRepository => (super.noSuchMethod(
        Invocation.getter(#storageRepository),
        returnValue: _FakeStorageRepository_2(
          this,
          Invocation.getter(#storageRepository),
        ),
      ) as _i2.StorageRepository);

  @override
  _i5.UserStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.UserStatus.initial,
      ) as _i5.UserStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<String> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set setCurrentUser(_i3.AppUser? appUser) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentUser,
          appUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBlockedUsers(List<String>? blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #setBlockedUsers,
          blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> createUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> readUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfileVisibility(String? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [newValue],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> updateProfile({
    required _i3.AppUser? appUser,
    _i6.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #appUser: appUser,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroState extends _i1.Mock implements _i8.MunroState {
  MockMunroState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MunroRepository get munroRepository => (super.noSuchMethod(
        Invocation.getter(#munroRepository),
        returnValue: _FakeMunroRepository_4(
          this,
          Invocation.getter(#munroRepository),
        ),
      ) as _i2.MunroRepository);

  @override
  _i8.MunroStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i8.MunroStatus.initial,
      ) as _i8.MunroStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<_i3.Munro> get munroList => (super.noSuchMethod(
        Invocation.getter(#munroList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  List<_i3.Munro> get filteredMunroList => (super.noSuchMethod(
        Invocation.getter(#filteredMunroList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  _i9.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i9.SortOrder.alphabetical,
      ) as _i9.SortOrder);

  @override
  _i3.FilterOptions get filterOptions => (super.noSuchMethod(
        Invocation.getter(#filterOptions),
        returnValue: _FakeFilterOptions_5(
          this,
          Invocation.getter(#filterOptions),
        ),
      ) as _i3.FilterOptions);

  @override
  bool get isFilterOptionsSet => (super.noSuchMethod(
        Invocation.getter(#isFilterOptionsSet),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.Munro> get createPostFilteredMunroList => (super.noSuchMethod(
        Invocation.getter(#createPostFilteredMunroList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  List<_i3.Munro> get bulkMunroUpdateList => (super.noSuchMethod(
        Invocation.getter(#bulkMunroUpdateList),
        returnValue: <_i3.Munro>[],
      ) as List<_i3.Munro>);

  @override
  set setStatus(_i8.MunroStatus? searchStatus) => super.noSuchMethod(
        Invocation.setter(
          #setStatus,
          searchStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.setter(
          #setError,
          error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setMunroList(List<_i3.Munro>? munroList) => super.noSuchMethod(
        Invocation.setter(
          #setMunroList,
          munroList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunro(_i3.Munro? selectedMunro) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunro,
          selectedMunro,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSelectedMunroId(int? selectedMunroId) => super.noSuchMethod(
        Invocation.setter(
          #setSelectedMunroId,
          selectedMunroId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setLatLngBounds(_i10.LatLngBounds? bounds) => super.noSuchMethod(
        Invocation.setter(
          #setLatLngBounds,
          bounds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setSortOrder(_i9.SortOrder? sortOrder) => super.noSuchMethod(
        Invocation.setter(
          #setSortOrder,
          sortOrder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setFilterOptions(_i3.FilterOptions? filterOptions) => super.noSuchMethod(
        Invocation.setter(
          #setFilterOptions,
          filterOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setGroupFilterMunroIds(List<int>? groupFilterMunroIds) =>
      super.noSuchMethod(
        Invocation.setter(
          #setGroupFilterMunroIds,
          groupFilterMunroIds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setCreatePostFilterString(String? filterString) => super.noSuchMethod(
        Invocation.setter(
          #setCreatePostFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBulkMunroUpdateFilterString(String? filterString) =>
      super.noSuchMethod(
        Invocation.setter(
          #setBulkMunroUpdateFilterString,
          filterString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadMunros() => (super.noSuchMethod(
        Invocation.method(
          #loadMunros,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void syncCompletedIds(Set<int>? ids) => super.noSuchMethod(
        Invocation.method(
          #syncCompletedIds,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilterAndSorting() => super.noSuchMethod(
        Invocation.method(
          #clearFilterAndSorting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );
}
