// Mocks generated by Mockito 5.4.6 from annotations
// in two_eight_two/test/screens/create_post/state/create_post_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:two_eight_two/analytics/analytics.dart' as _i10;
import 'package:two_eight_two/logging/logging.dart' as _i11;
import 'package:two_eight_two/models/models.dart' as _i3;
import 'package:two_eight_two/repos/repos.dart' as _i2;
import 'package:two_eight_two/screens/notifiers.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUserRepository_1 extends _i1.SmartFake
    implements _i2.BlockedUserRepository {
  _FakeBlockedUserRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRepository_2 extends _i1.SmartFake
    implements _i2.StorageRepository {
  _FakeStorageRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeError_3 extends _i1.SmartFake implements _i3.Error {
  _FakeError_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunroCompletionsRepository_4 extends _i1.SmartFake
    implements _i2.MunroCompletionsRepository {
  _FakeMunroCompletionsRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_5 extends _i1.SmartFake implements _i4.UserState {
  _FakeUserState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfig_6 extends _i1.SmartFake implements _i3.RemoteConfig {
  _FakeRemoteConfig_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsRepository extends _i1.Mock implements _i2.PostsRepository {
  MockPostsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> create({required _i3.Post? post}) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#post: post},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [],
            {#post: post},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<dynamic> update({required _i3.Post? post}) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#post: post},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Post?> readPostFromUid({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readPostFromUid,
          [],
          {#uid: uid},
        ),
        returnValue: _i5.Future<_i3.Post?>.value(),
      ) as _i5.Future<_i3.Post?>);

  @override
  _i5.Future<List<_i3.Post>> readPostsFromUserId({
    required String? userId,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readPostsFromUserId,
          [],
          {
            #userId: userId,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i3.Post>>.value(<_i3.Post>[]),
      ) as _i5.Future<List<_i3.Post>>);

  @override
  _i5.Future<List<_i3.Post>> getFriendsFeedFromUserId({
    required String? userId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendsFeedFromUserId,
          [],
          {
            #userId: userId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i3.Post>>.value(<_i3.Post>[]),
      ) as _i5.Future<List<_i3.Post>>);

  @override
  _i5.Future<List<_i3.Post>> getGlobalFeed({
    required List<String>? excludedAuthorIds,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalFeed,
          [],
          {
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i3.Post>>.value(<_i3.Post>[]),
      ) as _i5.Future<List<_i3.Post>>);

  @override
  _i5.Future<dynamic> deletePostWithUID({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePostWithUID,
          [],
          {#uid: uid},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}

/// A class which mocks [MunroPicturesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroPicturesRepository extends _i1.Mock
    implements _i2.MunroPicturesRepository {
  MockMunroPicturesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.MunroPicture>> readMunroPictures({
    required int? munroId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
    int? count = 18,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readMunroPictures,
          [],
          {
            #munroId: munroId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
            #count: count,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.MunroPicture>>.value(<_i3.MunroPicture>[]),
      ) as _i5.Future<List<_i3.MunroPicture>>);

  @override
  _i5.Future<List<_i3.MunroPicture>> readProfilePictures({
    required String? profileId,
    required List<String>? excludedAuthorIds,
    int? offset = 0,
    int? count = 18,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readProfilePictures,
          [],
          {
            #profileId: profileId,
            #excludedAuthorIds: excludedAuthorIds,
            #offset: offset,
            #count: count,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.MunroPicture>>.value(<_i3.MunroPicture>[]),
      ) as _i5.Future<List<_i3.MunroPicture>>);

  @override
  _i5.Future<void> createMunroPictures(
          {required List<_i3.MunroPicture>? munroPictures}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMunroPictures,
          [],
          {#munroPictures: munroPictures},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> deleteMunroPicturesByUrls(
          {required List<String>? imageURLs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMunroPicturesByUrls,
          [],
          {#imageURLs: imageURLs},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i2.StorageRepository {
  MockStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> uploadImage({
    required _i7.File? imageFile,
    required _i2.ImageUploadType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [],
          {
            #imageFile: imageFile,
            #type: type,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {
              #imageFile: imageFile,
              #type: type,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> deleteByUrl(String? imageUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteByUrl,
          [imageUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [UserState].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserState extends _i1.Mock implements _i4.UserState {
  MockUserState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);

  @override
  _i2.BlockedUserRepository get blockedUserRepository => (super.noSuchMethod(
        Invocation.getter(#blockedUserRepository),
        returnValue: _FakeBlockedUserRepository_1(
          this,
          Invocation.getter(#blockedUserRepository),
        ),
      ) as _i2.BlockedUserRepository);

  @override
  _i2.StorageRepository get storageRepository => (super.noSuchMethod(
        Invocation.getter(#storageRepository),
        returnValue: _FakeStorageRepository_2(
          this,
          Invocation.getter(#storageRepository),
        ),
      ) as _i2.StorageRepository);

  @override
  _i4.UserStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.UserStatus.initial,
      ) as _i4.UserStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<String> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set setCurrentUser(_i3.AppUser? appUser) => super.noSuchMethod(
        Invocation.setter(
          #setCurrentUser,
          appUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setBlockedUsers(List<String>? blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #setBlockedUsers,
          blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> createUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> readUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser({required _i3.AppUser? appUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#appUser: appUser},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> blockUser({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfileVisibility(String? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [newValue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> updateProfile({
    required _i3.AppUser? appUser,
    _i7.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #appUser: appUser,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MunroCompletionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockMunroCompletionState extends _i1.Mock
    implements _i4.MunroCompletionState {
  MockMunroCompletionState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MunroCompletionsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMunroCompletionsRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MunroCompletionsRepository);

  @override
  _i4.UserState get userState => (super.noSuchMethod(
        Invocation.getter(#userState),
        returnValue: _FakeUserState_5(
          this,
          Invocation.getter(#userState),
        ),
      ) as _i4.UserState);

  @override
  _i4.MunroCompletionsStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.MunroCompletionsStatus.initial,
      ) as _i4.MunroCompletionsStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  List<_i3.MunroCompletion> get munroCompletions => (super.noSuchMethod(
        Invocation.getter(#munroCompletions),
        returnValue: <_i3.MunroCompletion>[],
      ) as List<_i3.MunroCompletion>);

  @override
  Set<int> get completedMunroIds => (super.noSuchMethod(
        Invocation.getter(#completedMunroIds),
        returnValue: <int>{},
      ) as Set<int>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadUserMunroCompletions() => (super.noSuchMethod(
        Invocation.method(
          #loadUserMunroCompletions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addBulkCompletions(
          {required List<_i3.MunroCompletion>? munroCompletions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBulkCompletions,
          [],
          {#munroCompletions: munroCompletions},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markMunrosAsCompleted({
    required List<int>? munroIds,
    required DateTime? dateTimeCompleted,
    DateTime? completionDate,
    _i9.TimeOfDay? completionStartTime,
    Duration? completionDuration,
    String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMunrosAsCompleted,
          [],
          {
            #munroIds: munroIds,
            #dateTimeCompleted: dateTimeCompleted,
            #completionDate: completionDate,
            #completionStartTime: completionStartTime,
            #completionDuration: completionDuration,
            #postId: postId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMunroCompletion(
          {required _i3.MunroCompletion? munroCompletion}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMunroCompletion,
          [],
          {#munroCompletion: munroCompletion},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCompletionsByMunroIdsAndPost({
    required List<int>? munroIds,
    required String? postId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCompletionsByMunroIdsAndPost,
          [],
          {
            #munroIds: munroIds,
            #postId: postId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMunroCompletionsByMunroIdsAndPost({
    required List<int>? munroIds,
    required String? postId,
    required DateTime? dateTimeCompleted,
    DateTime? completionDate,
    _i9.TimeOfDay? completionStartTime,
    Duration? completionDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMunroCompletionsByMunroIdsAndPost,
          [],
          {
            #munroIds: munroIds,
            #postId: postId,
            #dateTimeCompleted: dateTimeCompleted,
            #completionDate: completionDate,
            #completionStartTime: completionStartTime,
            #completionDuration: completionDuration,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setError(_i3.Error? error) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RemoteConfigState].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigState extends _i1.Mock implements _i4.RemoteConfigState {
  MockRemoteConfigState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RemoteConfigStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.RemoteConfigStatus.initial,
      ) as _i4.RemoteConfigStatus);

  @override
  _i3.Error get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeError_3(
          this,
          Invocation.getter(#error),
        ),
      ) as _i3.Error);

  @override
  _i3.RemoteConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeRemoteConfig_6(
          this,
          Invocation.getter(#config),
        ),
      ) as _i3.RemoteConfig);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Analytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalytics extends _i1.Mock implements _i10.Analytics {
  MockAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> track(
    String? name, {
    Map<String, Object?>? props,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #track,
          [name],
          {#props: props},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> identify(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    Object? error, {
    StackTrace? stackTrace,
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [error],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, Object?>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identify(String? userId) => super.noSuchMethod(
        Invocation.method(
          #identify,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
