create table "public"."app_config" (
    "key" text not null,
    "value" text not null
);


create table "public"."test_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX app_config_pkey ON public.app_config USING btree (key);

CREATE UNIQUE INDEX test_table_pkey ON public.test_table USING btree (id);

alter table "public"."app_config" add constraint "app_config_pkey" PRIMARY KEY using index "app_config_pkey";

alter table "public"."test_table" add constraint "test_table_pkey" PRIMARY KEY using index "test_table_pkey";

grant delete on table "public"."app_config" to "anon";

grant insert on table "public"."app_config" to "anon";

grant references on table "public"."app_config" to "anon";

grant select on table "public"."app_config" to "anon";

grant trigger on table "public"."app_config" to "anon";

grant truncate on table "public"."app_config" to "anon";

grant update on table "public"."app_config" to "anon";

grant delete on table "public"."app_config" to "authenticated";

grant insert on table "public"."app_config" to "authenticated";

grant references on table "public"."app_config" to "authenticated";

grant select on table "public"."app_config" to "authenticated";

grant trigger on table "public"."app_config" to "authenticated";

grant truncate on table "public"."app_config" to "authenticated";

grant update on table "public"."app_config" to "authenticated";

grant delete on table "public"."app_config" to "service_role";

grant insert on table "public"."app_config" to "service_role";

grant references on table "public"."app_config" to "service_role";

grant select on table "public"."app_config" to "service_role";

grant trigger on table "public"."app_config" to "service_role";

grant truncate on table "public"."app_config" to "service_role";

grant update on table "public"."app_config" to "service_role";

grant delete on table "public"."test_table" to "anon";

grant insert on table "public"."test_table" to "anon";

grant references on table "public"."test_table" to "anon";

grant select on table "public"."test_table" to "anon";

grant trigger on table "public"."test_table" to "anon";

grant truncate on table "public"."test_table" to "anon";

grant update on table "public"."test_table" to "anon";

grant delete on table "public"."test_table" to "authenticated";

grant insert on table "public"."test_table" to "authenticated";

grant references on table "public"."test_table" to "authenticated";

grant select on table "public"."test_table" to "authenticated";

grant trigger on table "public"."test_table" to "authenticated";

grant truncate on table "public"."test_table" to "authenticated";

grant update on table "public"."test_table" to "authenticated";

grant delete on table "public"."test_table" to "service_role";

grant insert on table "public"."test_table" to "service_role";

grant references on table "public"."test_table" to "service_role";

grant select on table "public"."test_table" to "service_role";

grant trigger on table "public"."test_table" to "service_role";

grant truncate on table "public"."test_table" to "service_role";

grant update on table "public"."test_table" to "service_role";

CREATE TRIGGER "On Comment Created Webhook" AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://pqgaczyxzxopkgyjqudk.supabase.co/functions/v1/on-comment-created', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2Fjenl4enhvcGtneWpxdWRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTg1NDM0MSwiZXhwIjoyMDY1NDMwMzQxfQ.S9N6gXuqCX6i3yfSqYHrP_X-P5gG8SK2yWYRm2Efm2M"}', '{}', '5000');

CREATE TRIGGER "On Follower Created Webhook" AFTER INSERT ON public.followers FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://pqgaczyxzxopkgyjqudk.supabase.co/functions/v1/on-follower-created', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2Fjenl4enhvcGtneWpxdWRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTg1NDM0MSwiZXhwIjoyMDY1NDMwMzQxfQ.S9N6gXuqCX6i3yfSqYHrP_X-P5gG8SK2yWYRm2Efm2M"}', '{}', '5000');

CREATE TRIGGER "On Like Created Webhook" AFTER INSERT ON public.likes FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://pqgaczyxzxopkgyjqudk.supabase.co/functions/v1/on-like-created', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2Fjenl4enhvcGtneWpxdWRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTg1NDM0MSwiZXhwIjoyMDY1NDMwMzQxfQ.S9N6gXuqCX6i3yfSqYHrP_X-P5gG8SK2yWYRm2Efm2M"}', '{}', '5000');

CREATE TRIGGER "On Notification Created Webhook" AFTER INSERT ON public.notifications FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://pqgaczyxzxopkgyjqudk.supabase.co/functions/v1/on-notification-created', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2Fjenl4enhvcGtneWpxdWRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTg1NDM0MSwiZXhwIjoyMDY1NDMwMzQxfQ.S9N6gXuqCX6i3yfSqYHrP_X-P5gG8SK2yWYRm2Efm2M"}', '{}', '5000');

CREATE TRIGGER "On User Created Webhook" AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://pqgaczyxzxopkgyjqudk.supabase.co/functions/v1/on-user-created', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2Fjenl4enhvcGtneWpxdWRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTg1NDM0MSwiZXhwIjoyMDY1NDMwMzQxfQ.S9N6gXuqCX6i3yfSqYHrP_X-P5gG8SK2yWYRm2Efm2M"}', '{}', '5000');


